const { contextBridge, ipcRenderer } = require('electron');

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('api', {
    company: {
        create:         (data) => invoke('company:create', data),
        getAll:         ()     => invoke('company:getAll'),
        getById:        (id)   => invoke('company:getById', id),
        update:         (data) => invoke('company:update', data),
        delete:         (id)   => invoke('company:delete', id),
        verifyPassword: (data) => invoke('company:verifyPassword', data),
    },
    fy: {
        create:   (data) => invoke('fy:create', data),
        getAll:   ()     => invoke('fy:getAll'),
        getById:  (id)   => invoke('fy:getById', id),
        setActive:(id)   => invoke('fy:setActive', id),
        delete:   (id)   => invoke('fy:delete', id),
    },
    group: {
        create:  (data) => invoke('group:create', data),
        getAll:  ()     => invoke('group:getAll'),
        getById: (id)   => invoke('group:getById', id),
        update:  (data) => invoke('group:update', data),
        delete:  (id)   => invoke('group:delete', id),
        getTree: ()     => invoke('group:getTree'),
    },
    ledger: {
        create:     (data)    => invoke('ledger:create', data),
        getAll:     ()        => invoke('ledger:getAll'),
        getById:    (id)      => invoke('ledger:getById', id),
        update:     (data)    => invoke('ledger:update', data),
        delete:     (id)      => invoke('ledger:delete', id),
        getByGroup: (groupId) => invoke('ledger:getByGroup', groupId),
    },
    costCentre: {
        create:  (data) => invoke('costCentre:create', data),
        getAll:  ()     => invoke('costCentre:getAll'),
        getById: (id)   => invoke('costCentre:getById', id),
        update:  (data) => invoke('costCentre:update', data),
        delete:  (id)   => invoke('costCentre:delete', id),
        getTree: ()     => invoke('costCetre:getTree'),
    },
    unit: {
        create:  (data) => invoke('unit:create', data),
        getAll:  ()     => invoke('unit:getAll'),
        getById: (id)   => invoke('unit:getById', id),
        update:  (data) => invoke('unit:update', data),
        delete:  (id)   => invoke('unit:delete', id),
    },
    stockGroup: {
        create:  (data) => invoke('stockGroup:create', data),
        getAll:  ()     => invoke('stockGroup:getAll'),
        getById: (id)   => invoke('stockGroup:getById', id),
        update:  (data) => invoke('stockGroup:update', data),
        delete:  (id)   => invoke('stockGroup:delete', id),
        getTree: ()     => invoke('stockGroup:getTree'),
    },
    stockCategory: {
        create:  (data) => invoke('stockCategory:create', data),
        getAll:  ()     => invoke('stockCategory:getAll'),
        getById: (id)   => invoke('stockCategory:getById', id),
        update:  (data) => invoke('stockCategory:update', data),
        delete:  (id)   => invoke('stockCategory:delete', id),
    },
    stockItem: {
        create:      (data)       => invoke('stockItem:create', data),
        getAll:      ()           => invoke('stockItem:getAll'),
        getById:     (id)         => invoke('stockItem:getById', id),
        update:      (data)       => invoke('stockItem:update', data),
        delete:      (id)         => invoke('stockItem:delete', id),
        getByGroup:  (groupId)    => invoke('stockItem:getByGroup', groupId),
        getByCategory:(categoryId)=> invoke('stockItem:getByCategory', categoryId),
    },
    godown: {
        create:  (data) => invoke('godown:create', data),
        getAll:  ()     => invoke('godown:getAll'),
        getById: (id)   => invoke('godown:getById', id),
        update:  (data) => invoke('godown:update', data),
        delete:  (id)   => invoke('godown:delete', id),
        getTree: ()     => invoke('godown:getTree'),
    },
    voucher: {
        create:     (data)     => invoke('voucher:create', data),
        getAll:     ()         => invoke('voucher:getAll'),
        getById:    (id)       => invoke('voucher:getById', id),
        update:     (data)     => invoke('voucher:update', data),
        delete:     (id)       => invoke('voucher:delete', id),
        cancel:     (id)       => invoke('voucher:cancel', id),
        getDaybook: (filters)  => invoke('voucher:getDaybook', filters),
        getByType:  (type)     => invoke('voucher:getByType', type),
        getByLedger:(ledgerId) => invoke('voucher:getByLedger', ledgerId),
    },
    report: {
        trialBalance: (filters) => invoke('report:trialBalance', filters),
        balanceSheet: (filters) => invoke('report:balanceSheet', filters),
        profitLoss:   (filters) => invoke('report:profitLoss', filters),
        ledgerReport: (filters) => invoke('report:ledgerReport', filters),
        cashBook:     (filters) => invoke('report:cashBook', filters),
        bankBook:     (filters) => invoke('report:bankBook', filters),
        daybook:      (filters) => invoke('report:daybook', filters),
    },
    banking: {
        getUnreconciled: (ledgerId) => invoke('banking:getUnreconciled', ledgerId),
        reconcile:       (data)     => invoke('banking:reconcile', data),
        unreconcile:     (data)     => invoke('banking:unreconcile', data),
        getStatement:    (filters)  => invoke('banking:getStatement', filters),
        getSummary:      (ledgerId) => invoke('banking:getSummary', ledgerId),
    },
    currency: {
        create:     (data) => invoke('currency:create', data),
        getAll:     ()     => invoke('currency:getAll'),
        getById:    (id)   => invoke('currency:getById', id),
        update:     (data) => invoke('currency:update', data),
        delete:     (id)   => invoke('currency:delete', id),
        setDefault: (id)   => invoke('currency:setDefault', id),
    },
    voucherType: {
        create:       (data) => invoke('voucherType:create', data),
        getAll:       ()     => invoke('voucherType:getAll'),
        getById:      (id)   => invoke('voucherType:getById', id),
        update:       (data) => invoke('voucherType:update', data),
        delete:       (id)   => invoke('voucherType:delete', id),
        getConfig:    (id)   => invoke('voucherType:getConfig', id),
        updateConfig: (data) => invoke('voucherType:updateConfig', data),
    },
    gstRegistration: {
        create:  (data) => invoke('gstRegistration:create', data),
        getAll:  ()     => invoke('gstRegistration:getAll'),
        getById: (id)   => invoke('gstRegistration:getById', id),
        update:  (data) => invoke('gstRegistration:update', data),
        delete:  (id)   => invoke('gstRegistration:delete', id),
    },
    gstClassification: {
        create:  (data) => invoke('gstClassification:create', data),
        getAll:  ()     => invoke('gstClassification:getAll'),
        getById: (id)   => invoke('gstClassification:getById', id),
        update:  (data) => invoke('gstClassification:update', data),
        delete:  (id)   => invoke('gstClassification:delete', id),
    },
});