const { pgTable, bigint, text, integer, real, boolean, timestamp } = require('drizzle-orm/pg-core');
const { companies } = require('./company');

// Follows docs/db/modules/taxUnits.sql.
// tax_unit_id: BIGINT GENERATED BY DEFAULT AS IDENTITY PK.
// 0/1 flags (set_alter_*, is_active) -> BOOLEAN; sort_order -> INTEGER;
// created_at/updated_at -> TIMESTAMPTZ DEFAULT now().
// company_id is an EXPLICIT FK to companies(company_id) ON DELETE CASCADE.
const taxUnits = pgTable('tax_units', {
  taxUnitId: bigint('tax_unit_id', { mode: 'number' })
    .primaryKey()
    .generatedByDefaultAsIdentity(),
  companyId: bigint('company_id', { mode: 'number' })
    .notNull()
    .references(() => companies.companyId, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  alias: text('alias'),
  addressLine1: text('address_line1'),
  addressLine2: text('address_line2'),
  addressLine3: text('address_line3'),
  addressLine4: text('address_line4'),
  state: text('state'),
  pincode: text('pincode'),
  telephone: text('telephone'),
  registeredFor: text('registered_for').notNull().default('Excise'),
  setAlterExciseDetails: boolean('set_alter_excise_details').notNull().default(false),
  registrationType: text('registration_type').notNull().default('Importer'),
  typeOfManufacturer: text('type_of_manufacturer'),
  eccNumber: text('ecc_number'),
  setAlterExciseTariff: boolean('set_alter_excise_tariff').notNull().default(false),
  tariffName: text('tariff_name'),
  hsnCode: text('hsn_code'),
  reportingUom: text('reporting_uom'),
  valuationType: text('valuation_type'),
  tariffRate: real('tariff_rate').default(0),
  tariffRatePerUnit: real('tariff_rate_per_unit').default(0),
  setAlterRule11Book: boolean('set_alter_rule11_book').notNull().default(false),
  rule11Book: text('rule11_book'),
  sortOrder: integer('sort_order').notNull().default(0),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

module.exports = {
  taxUnits,
};
